server:
  port: 8086  # The port your service will run on

spring:
  application:
    name: customerservice  # Use lowercase, no dash for consistency with Eureka

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG

