server:
  port: 8086  # The port your service will run on

spring:
  application:
    name: customer-service  # Unique name of the service
  cloud:
    discovery:
      enabled: true
      eureka:
        client:
          serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/  # Eureka Server URL

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
